services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_db_user
      POSTGRES_PASSWORD: todo_db_pass

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

      # healthcheck:
      #   test: ["CMD-SHELL", "db_isready -U db_user -d db"]
      #   interval: 10s
      #   timeout: 5s
      #   reties: 5

volumes:
  db_data:
